import { Wrap as YogaWrap, PositionType as YogaPositionType, Node as YogaNode, Align as YogaAlign, Justify as YogaJustify, FlexDirection as YogaFlexDirection, Display as YogaDisplay, Gutter as YogaGutter, Edge as YogaEdge, BoxSizing as YogaBoxSizing, Overflow as YogaOverflow } from "yoga-layout";
import { YogaValue, YogaValueAuto } from "../layout/layout.js";

export interface LayoutStyle {
    align_content: YogaAlign;
    align_items: YogaAlign;
    justify_content: YogaJustify;
    aspect_ratio: number;
    display: YogaDisplay;
    gap: YogaValue;
    gap_column: YogaValue;
    gap_row: YogaValue;
    flex_direction: YogaFlexDirection;
    flex_basis: YogaValueAuto;
    flex_grow: number;
    flex_shrink: number;
    flex_wrap: YogaWrap;
    top: YogaValueAuto;
    left: YogaValueAuto;
    bottom: YogaValueAuto;
    right: YogaValueAuto;
    width: YogaValueAuto;
    min_width: YogaValue;
    max_width: YogaValue;
    height: YogaValueAuto;
    min_height: YogaValue;
    max_height: YogaValue;
    margin: YogaValueAuto;
    margin_top: YogaValueAuto;
    margin_right: YogaValueAuto;
    margin_bottom: YogaValueAuto;
    margin_left: YogaValueAuto;
    margin_start: YogaValueAuto;
    margin_end: YogaValueAuto;
    margin_horizontal: YogaValueAuto;
    margin_vertical: YogaValueAuto;
    padding: YogaValue;
    padding_top: YogaValue;
    padding_right: YogaValue;
    padding_bottom: YogaValue;
    padding_left: YogaValue;
    padding_start: YogaValue;
    padding_end: YogaValue;
    padding_horizontal: YogaValue;
    padding_vertical: YogaValue;
    position: YogaPositionType;
    border: number | undefined;
    border_top: number | undefined;
    border_right: number | undefined;
    border_bottom: number | undefined;
    border_left: number | undefined;
    border_start: number | undefined;
    border_end: number | undefined;
    border_horizontal: number | undefined;
    border_vertical: number | undefined;
    box_sizing: YogaBoxSizing;
    overflow: YogaOverflow;
}